name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      
      - name: Install deps
        run: deno install

      - name: Publish package
        run: deno publish
